name: "[Testing] Build generated API docs pages for beta site"

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Runs on pushes targeting the default branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  # Build job
  build:
    # We believe there is a dependency on Windows due to a WinForms element somewhere in Meadow that DocFX hits. Ideally, it wouldn't be a requirement, though.
    #runs-on: ubuntu-latest
    runs-on: windows-latest
    
    steps:
      - name: Debug output
        run: |
          echo "${GITHUB_REF}"

      # Check out this content repo.
      - name: Checkout Documentation side-by-side
        uses: actions/checkout@v3
        with:
          path: src
          
      # Clone all the Meadow dependencies adjacent for DocFX build use.
      - name: Checkout Meadow.Units side-by-side
        uses: actions/checkout@v3
        with:
          repository: WildernessLabs/Meadow.Units
          path: Meadow.Units
          ref: develop
          
      - name: Checkout Meadow.Logging side-by-side
        uses: actions/checkout@v3
        with:
          repository: WildernessLabs/Meadow.Logging
          path: Meadow.Logging
          ref: develop
          
      - name: Checkout Meadow.Contracts side-by-side
        uses: actions/checkout@v3
        with:
          repository: WildernessLabs/Meadow.Contracts
          path: Meadow.Contracts
          ref: develop
          
      - name: Checkout Meadow.Modbus side-by-side
        uses: actions/checkout@v3
        with:
          repository: WildernessLabs/Meadow.Modbus
          path: Meadow.Modbus
          ref: develop
          
      - name: Checkout Meadow.Foundation side-by-side
        uses: actions/checkout@v3
        with:
          repository: WildernessLabs/Meadow.Foundation
          path: Meadow.Foundation
          ref: develop
          
      - name: Checkout Meadow.Core side-by-side
        uses: actions/checkout@v3
        with:
          repository: WildernessLabs/Meadow.Core
          path: Meadow.Core
          ref: develop

      - name: Checkout MQTTnet side-by-side
        uses: actions/checkout@v3
        with:
          repository: WildernessLabs/MQTTnet
          path: MQTTnet
          ref: develop
          
      - name: Checkout Meadow side-by-side
        uses: actions/checkout@v3
        with:
          # Private repo requires token access; rest are public repos.
          token: ${{ secrets.CI_ACCESS_TOKEN }}
          repository: WildernessLabs/Meadow
          path: Meadow
          ref: main # No develop branch on Meadow [yet]
          
      # Clone more Meadow-related repos for API docs generation (via DocFX).
      - name: Checkout Meadow.Foundation.Grove into DocFX-expected Source location
        uses: actions/checkout@v3
        with:
          repository: WildernessLabs/Meadow.Foundation.Grove
          path: Meadow.Foundation.Grove
          ref: develop
          
      - name: Checkout Meadow.Foundation.FeatherWings into DocFX-expected Source location
        uses: actions/checkout@v3
        with:
          repository: WildernessLabs/Meadow.Foundation.FeatherWings
          path: Meadow.Foundation.FeatherWings
          ref: develop
          
      - name: Checkout Meadow.Foundation.mikroBUS into DocFX-expected Source location
        uses: actions/checkout@v3
        with:
          repository: WildernessLabs/Meadow.Foundation.mikroBUS
          path: Meadow.Foundation.mikroBUS
          ref: develop

      - name: Setup .NET Core SDK 6.0.x & 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x

      - name: Setup NuGet
        uses: Nuget/setup-nuget@v1.0.5

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install DocFX globally
        run: |
          dotnet tool install --global docfx

      - name: Run DocFX
        run: |
          cd src/docfx
          docfx docfx.json

      - name: Clean up some generated DocFX TOC output
        run: |
          cd src/docfx
          (cat .\docs\api\Meadow\toc.html) | % { $_ -replace ">Meadow.Peripherals.", ">" } > .\docs\api\Meadow\toc.html
          (cat .\docs\api\Meadow.Foundation\toc.html) | % { $_ -replace ">Meadow.Foundation.", ">" } > .\docs\api\Meadow.Foundation\toc.html
          (cat .\docs\api\Meadow.Foundation\toc.html) | % { $_ -replace ">/a>", ">Meadow.Foundation</a>" } > .\docs\api\Meadow.Foundation\toc.html

      - if: ${{ (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/develop') || (github.ref == 'refs/heads/dominique-Fix440') }}
        name: Sync site to beta site
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          AWS_S3_BUCKET: 'beta-developer.wildernesslabs.co'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: src/docfx/docs
          DEST_DIR: docs/api-test
        # TODO with:
        # TODO  args: --delete
